#!/usr/bin/python
from __future__ import division
import sys, time
sys.path.append("build/lib.linux-i686-2.4")
import cam, vision
import pygame
import Image, ImageFilter
import Numeric as num
from multiimage import MultiImage

def writeArray():
    raise NotImplementedError
    h,w = L.shape
    b = num.repeat(L, 3, 1)
    b.shape = h,w,3   
    Image.fromstring("RGB",
                     (b.shape[1], b.shape[0]),
                     num.clip(b, 0, 255).astype('b').tostring()
                     ).save("diff.ppm")
    

surf = pygame.display.set_mode((352 * 2, 288 * 2))

cam.grab_init("/dev/video0")
cam.set_pict(contrast=.6, brightness=.3)
while 1:
    t1 = time.time()
    i = MultiImage(cam.grab_frame(), 352, 288)
    print "grab %.04f" % (time.time() - t1)

    img = i.asSurface()
    #img.set_alpha(128)
    #img = pygame.transform.scale2x(img)
    surf.blit(img, (0, 0))
    print "draw %.04f" % (time.time() - t1)

    position = vision.findBlocks(i, surf)
    print position


    print "detect %.04f" % (time.time() - t1)
    
    pygame.display.update()
